### ISSUE TITLE
Fetch new href links

### ISSUE THREAD

**Issue by titipata** [titipata/grant_database#3]
We will modify bash or python later on if `data` is already existed, we will find new links > copy new zip file and parse that instead.

**Comment by bluenex** [comment]
To do so I think we need to collect all the links within `txt` file just like in `nsf`. If we fetch source again in the future it could be easier to check if something already exists. So, I will change the way we store the link in `nih`.

**Comment by titipata** [comment]
close by  0ba6e9c34379a8bc599d1f7. Thanks again @bluenex
