### ISSUE TITLE
Create code to merge NIH abstract with NIH grant information table

### ISSUE THREAD

**Issue by titipata** [titipata/grant_database#7]
This aim to include deduplicated authors and affiliations across datasets also. Put some instruction on how to deduplicate the dataset. Related to issue #9 and #10

**Comment by titipata** [comment]
**Update:** We get skeleton code for deduplicate NSF 6df0cae7a8f00a7037a3523.

**Comment by daniel-acuna** [comment]
Too broad. Closing for now.
